[platformio]
default_envs = controlx4

[env:controlx4]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

# Die Relay-X4-Platine besitzt keine automatische BOOT/EN-Schaltung.
# Vor dem USB-Upload IO0 halten und EN kurz druecken.
board_upload.before_reset = no_reset

[env:controlx4-ota]
extends = env:controlx4
upload_protocol = espota
upload_port = controlx4.local
upload_flags =
    --port=3232
    --auth=${sysenv.CONTROLX4_OTA_PASSWORD}

